### ISSUE TITLE
Update to use node-plex-api 2.0

### ISSUE THREAD

**Issue by OverloadUT** [phillipj/node-plex-control#4]
Are you planning on updating this module to support the latest version of node-plex-api? Most notably you cannot use this module currently if your PMS requires authentication :(

(I've tried doing it myself, but I am banging my head against a brick wall regarding an exception being thrown inside the node.js core modules after I simply change the dependency to use the latest plex-api and running the mocha tests. I'm about ready to give up and just use node-plex-api without the handy control wrappers that this provides.)

**Comment by phillipj** [comment]
Absolutely! I'll get a new major version out before the weekend.

**Comment by phillipj** [comment]
I'm afraid I promised a bit too much here @OverloadUT :disappointed: Supporting plex-api v2.x was more work than I thought. And as I'm headed on a short vacation until friday next week now, I havent had time to finish the whole refactoring.

I'll continue ASAP and keep you updated.

**Comment by OverloadUT** [comment]
No problem at all! The only client method I'm using in my project currently is the one you don't actually yet support: playMedia. It took a hell of a lot of trial and error to figure out how to get it to work. Once you get this up to 2.0 I will be happy to contribute what I figured out as an ext in this module :)

**Comment by phillipj** [comment]
Sounds great! Looking forward to have playMedia support :)

**Comment by phillipj** [comment]
FYI I got alot further with this tonight. The XML to JSON convertion of tests and samples/fake responses are cumbersome. Will continue tomorrow evening.

**Comment by phillipj** [comment]
Landed with b7741bf4be

**Comment by OverloadUT** [comment]
Excellent! I will eventually migrate the playMedia stuff I have figured out in to this module. Still trying to figure out the exact gotchas, which are many!
